language: node_js
node_js:
  - '10.5.0'
cache:
  directories:
    - 'node_modules'
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
  - npm i -g npm@6.1.0
install:
  - npm ci
before_script:
  - psql -c 'create database "mm-test";' -U postgres
script:
  - npm run lint
  - npm run lint-sass
  - npm test

# before_deploy:
#   - npm run build-client # make the bundle
#   - rm -rf node_modules # omit from the tarball, since we skip cleanup
# deploy:
#   skip_cleanup: true # prevents travis from deleting the build
#   provider: heroku
#   app: YOUR-HEROKU-APP-NAME-HERE # see README
#   api_key:
#     secure: YOUR-***ENCRYPTED***-API-KEY-HERE # see README
